# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

In [5]:
array1 = np.random.random((3,3,3))
print(array1)

[[[0.9033607  0.45565956 0.63757055]
  [0.15884022 0.08422275 0.18799365]
  [0.89731692 0.06199169 0.02194803]]

 [[0.61684556 0.79282198 0.73196333]
  [0.5736133  0.58308952 0.78871576]
  [0.54864968 0.19973781 0.6834206 ]]

 [[0.53022562 0.42195062 0.14562625]
  [0.89672607 0.65450874 0.63863059]
  [0.95198746 0.15032912 0.34351676]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
y = np.zeros((8,8),dtype=int)
y[1::2,::2] = 1
y[::2,1::2] = 1
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [9]:
z = np.random.random((5,5))
z = (z - np.mean (z)) / (np.std (z))
print(z)

[[-1.52883857  0.4045548  -1.18154327  1.1898297  -1.10845499]
 [ 0.96777966  0.55481547 -0.80777529  1.10624287  0.2494333 ]
 [ 0.95652326  0.35855201  1.02471364  0.2231024  -0.63676689]
 [-0.77226221  1.72985806  0.47899442 -0.62656689  1.61926921]
 [ 0.02242858 -0.06495264 -1.10378465 -1.48288415 -1.57226785]]


# 5.  How to find common values between two arrays?

In [13]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[1 4 5 6 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-30
2020-07-31
2020-08-01


# 7. Consider two random array A and B, check if they are equal

In [14]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [16]:
a1 = np.random.random(10)
a1[a1.argmax()] = 0
print(a1)

[0.7030308  0.         0.8603135  0.15152438 0.12547198 0.13504511
 0.5319289  0.82697482 0.696896   0.26160002]


# 9. How to print all the values of an array?

In [17]:
np.set_printoptions(threshold=float("inf"))
d = np.zeros((16,16))
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [18]:
a = np.random.rand(5, 10)

b = a - a.mean(axis=1, keepdims=True)

b1 = a - a.mean(axis=1).reshape(-1, 1)

print(b)
print(b1)

[[ 0.3418159   0.16596757 -0.06604819 -0.41193569  0.52930647  0.04864691
   0.13635574 -0.29945194 -0.40739847 -0.0372583 ]
 [ 0.34778307  0.42067144  0.36643971 -0.41576965  0.06191767 -0.05220702
  -0.30542853  0.03232542  0.02253108 -0.47826321]
 [ 0.35999155 -0.15739321  0.33686779 -0.16807716 -0.01910322 -0.09688168
   0.43468382 -0.16590475 -0.30123585 -0.2229473 ]
 [ 0.30772482 -0.249034   -0.23424425  0.57669467 -0.18810284 -0.01969804
  -0.24074132 -0.17848431 -0.03349098  0.25937624]
 [ 0.28529007  0.47990659 -0.40223186 -0.40776111  0.47172585 -0.41391217
  -0.15189049  0.1037168   0.09771248 -0.06255617]]
[[ 0.3418159   0.16596757 -0.06604819 -0.41193569  0.52930647  0.04864691
   0.13635574 -0.29945194 -0.40739847 -0.0372583 ]
 [ 0.34778307  0.42067144  0.36643971 -0.41576965  0.06191767 -0.05220702
  -0.30542853  0.03232542  0.02253108 -0.47826321]
 [ 0.35999155 -0.15739321  0.33686779 -0.16807716 -0.01910322 -0.09688168
   0.43468382 -0.16590475 -0.30123585 -0.2229473 ]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [20]:
a = np.ones(10)
I = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)

[3. 1. 2. 3. 4. 2. 2. 4. 2. 7.]


In [22]:
np.add.at(a, I, 1)
print(a)

[ 5.  1.  3.  5.  7.  3.  3.  7.  3. 13.]


# 12.How to get the diagonal of a dot product?

In [23]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)

pr1=np.diag(np.dot(A, B))

pr2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",pr1)
print("diagonal of a dot product method 2 is....",pr2)

[[0.54559277 0.36499668 0.84555152 0.06419819 0.87049368]
 [0.41447934 0.23747835 0.37903112 0.51171055 0.96122689]
 [0.4099028  0.12541507 0.88756679 0.04081594 0.79234585]
 [0.28048742 0.41516479 0.02409009 0.1567339  0.98280931]
 [0.52950536 0.78280021 0.20160521 0.21465828 0.9395213 ]]
[[0.17494361 0.50222215 0.50919139 0.31962725 0.23763491]
 [0.19837274 0.23784634 0.33138621 0.41132783 0.39427294]
 [0.61522991 0.12168488 0.02421368 0.34191976 0.42699552]
 [0.17132114 0.25621849 0.01877098 0.77461614 0.8236365 ]
 [0.5384262  0.06306906 0.82226633 0.87912614 0.33223615]]
diagonal of a dot product method 1 is.... [1.16775705 0.5024998  0.92405653 1.25407909 1.00949376]
diagonal of a dot product method 2 is.... [1.16775705 0.5024998  0.92405653 1.25407909 1.00949376]


# 13.How to find the most frequent value in an array?

In [24]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[0 8 2 8 3 0 8 6 6 5 4 9 4 2 2 1 2 4 1 4 9 9 0 1 0 3 9 6 9 8 7 6 2 7 2 6 5
 7 0 3 6 8 8 3 0 8 5 5 2 0]
0


# 14.How to get the n largest values of an array

In [29]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5


print (a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [30]:
z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
